// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_collect_200_stars = "CgkIlNfst8MVEAIQDw"; // <GPGSID>
        public const string achievement_collect_100_stars = "CgkIlNfst8MVEAIQDg"; // <GPGSID>
        public const string leaderboard_level_3 = "CgkIlNfst8MVEAIQAw"; // <GPGSID>
        public const string leaderboard_level_4 = "CgkIlNfst8MVEAIQBQ"; // <GPGSID>
        public const string leaderboard_level_5 = "CgkIlNfst8MVEAIQBg"; // <GPGSID>
        public const string leaderboard_level_6 = "CgkIlNfst8MVEAIQBw"; // <GPGSID>
        public const string leaderboard_level_7 = "CgkIlNfst8MVEAIQCA"; // <GPGSID>
        public const string leaderboard_level_8 = "CgkIlNfst8MVEAIQCQ"; // <GPGSID>
        public const string achievement_collect_30_diamonds = "CgkIlNfst8MVEAIQEQ"; // <GPGSID>
        public const string achievement_complete_a_level_with_no_long_jump = "CgkIlNfst8MVEAIQEg"; // <GPGSID>
        public const string leaderboard_level_2 = "CgkIlNfst8MVEAIQBA"; // <GPGSID>
        public const string achievement_collect_15_diamonds = "CgkIlNfst8MVEAIQEA"; // <GPGSID>
        public const string leaderboard_level_1 = "CgkIlNfst8MVEAIQAQ"; // <GPGSID>
        public const string achievement_complete_level_1 = "CgkIlNfst8MVEAIQAg"; // <GPGSID>
        public const string achievement_complete_level_10 = "CgkIlNfst8MVEAIQDQ"; // <GPGSID>
        public const string achievement_complete_level_5 = "CgkIlNfst8MVEAIQDA"; // <GPGSID>
        public const string leaderboard_level_10 = "CgkIlNfst8MVEAIQCw"; // <GPGSID>
        public const string leaderboard_level_9 = "CgkIlNfst8MVEAIQCg"; // <GPGSID>

}

